name: LawrenceWilburn
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60723
title: 'Brands for the people!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0157d'
    - '#25247d'
    - '#eb6c21'
    - '#fbf238'
    - '#92b526'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
